language: node_js
node_js:
  - '4'
  - 'node'

after_success:
  - npm run build

jobs:
  include:
    - node_js: 'node'
      deploy:
        provider: npm
        api_key: $NPM_API_KEY
        skip_cleanup: true
        on:
          - tags: true